### ISSUE TITLE
Investigate bug where all lines modified by both methods appear on both left and right modified line lists

### ISSUE THREAD

**Issue by rafaelmotaalves** [spgroup/miningframework#85]

**Comment by rafaelmotaalves** [comment]
some of the cases where the lines list are wrong are caused by unexpected behaviour by the diffj tool, here are some examples of those behaviors:

**Comment by rafaelmotaalves** [comment]
In this case where base is:

```java
    private void byClass() {
        String className = tq.consumeCssIdentifier();
        Validate.notEmpty(className);
        evals.add(new Evaluator.Class(className.trim().toLowerCase()));
    }

    private void byTag() {
        String tagName = tq.consumeElementSelector();
        Validate.notEmpty(tagName);

        // namespaces: if element name is "abc:def", selector must be "abc|def", so flip:
        if (tagName.contains("|"))
            tagName = tagName.replace("|", ":");

        evals.add(new Evaluator.Tag(tagName.trim().toLowerCase()));
    }
```
and right is:

```java
    private void byClass() {
        String className = tq.consumeCssIdentifier();
        Validate.notEmpty(className);
        evals.add(new Evaluator.Class(className.trim()));
    }

    private void byTag() {
        String tagName = tq.consumeElementSelector();
        Validate.notEmpty(tagName);

        // namespaces: if element name is "abc:def", selector must be "abc|def", so flip:
        if (tagName.contains("|"))
            tagName = tagName.replace("|", ":");

        evals.add(new Evaluator.Tag(tagName.trim()));
    }
```
diffj outputs:

```java
209d209 code removed in byClass()
<         evals.add(new Evaluator.Class(className.trim().toLowerCase()));
---
>         evals.add(new Evaluator.Class(className.trim()));

220d220 code removed in byTag()
<         evals.add(new Evaluator.Tag(tagName.trim().toLowerCase()));
---
>         evals.add(new Evaluator.Tag(tagName.trim()));
``` 
which is conceptually correct, but miningframework's codes expects that in this case, diffj would return *code changed*

**Comment by rafaelmotaalves** [comment]
forgot to tag you @pauloborba

**Comment by pauloborba** [comment]
@rafaelmotaalves so diffj only reports additions and removals? 

changes could be interpreted as a removal followed by an addition to the same line.

**Comment by rafaelmotaalves** [comment]
It has a changed flag, i think It uses something like an AST, so if the method name was changed, It would show change, but the method call was removed.

**Comment by pauloborba** [comment]
@rafaelmotaalves 

1. what is actually classified as a change by diffj?
2. interpret removed above as removal followed by addition
3. discuss and possibly transform change cases into removal followed by addition?

**Comment by rafaelmotaalves** [comment]
@pauloborba I created a repository with some examples of diffj's outputs in some cases: https://github.com/rafaelmotaalves/diffj-demo

**Comment by rafaelmotaalves** [comment]
The problem is that there is no way of distinguishing the case where some code is removed, and a full line is removed, those cases outputs can be seen on: [removed full line](https://github.com/rafaelmotaalves/diffj-demo/blob/master/remove-full-line/output.txt) and [removed code from line](https://github.com/rafaelmotaalves/diffj-demo/blob/master/remove-code-from-expression/output.txt)

**Comment by rafaelmotaalves** [comment]
also, here are some cases that diffj returns the code changed flag:

- [changed expression](https://github.com/rafaelmotaalves/diffj-demo/tree/master/change-expression)
- [changed method call](https://github.com/rafaelmotaalves/diffj-demo/tree/master/method-call-name-change)

**Comment by pauloborba** [comment]
@jvcoutinho can you have a look at that and let us your opinion? 

@rafaelmotaalves it seems that the "changed" cases are fine; they should all be added to the list we prepare and is used as input for the soot analysis. 

the "removed" cases are actually tricky, as you pointed out. maybe a way to distinguish line removal from line change would be to check if the text followed by ">" appears in the original version of the code. if it appears, we have a removal. otherwise, we have a change. as diffj output also includes line numbers (as in 4d4), we could maybe check if the contents of line 5 (4+1), in the example, is the same as the text appearing after ">" ("return name.toUpperCase();" in the first example). 

i wonder if this generalizes to other cases. it might also not be fully precise. if a developer removes a full line before o.m(), and adds a call o.n() just before o.m(), the algorithm above would say change, when there actually was a removal followed by an addition. could you please confirm that and the generalization aspect?

it would also be nice to check how the cases above behave in a purely textual merge. does diffj invokes diff3 for method bodies? I believe @jvcoutinho used diffj especially for detecting if the same method had been changed (is that the case @jvcoutinho?). for that, it's nice to have the syntactic diff. but for detecting lines changed, diff3 could actually be a better option. so one alternative would be to use the two tools in combination (unless diffj already invokes diff3 for method bodies).

**Comment by jvcoutinho** [comment]
It's weird. Maybe Diffj outputs _removed_ for every missing substring instead of a full line (the call `.toLowerCase()`, technically, has been removed, and the rest of the line remained the same). Some examples in the demo confirm this.

Following this hypotesis, we could adapt the code to check if the difference between the text followed by "<" and the one followed by ">" is a substring of the former.
Also, it might be worth to check if the _added_ label has the same behaviour.

> check if the text followed by ">" appears in the original version of the code. if it appears, we have a removal.

The problem with this is that the ">" text is usually the modified version.

>  I believe @jvcoutinho used diffj especially for detecting if the same method had been changed (is that the case @jvcoutinho?)

Yes.

**Comment by rafaelmotaalves** [comment]
> it would also be nice to check how the cases above behave in a purely textual merge. does diffj invokes diff3 for method bodies?

I don't think it does, because it uses the syntax tree inside the method.

>it's nice to have the syntactic diff. but for detecting lines changed, diff3 could actually be a better option. so one alternative would be to use the two tools in combination (unless diffj already invokes diff3 for method bodies).

So we would use DiffJ only to check line numbers and which method the changes were, and use a textual diff tool to resolve if the changes where adds, changes or removals? I think this could be a solution

**Comment by rafaelmotaalves** [comment]
Also, testing I tested using the textual diff tool and it returns our expected outputs for some of those cases.

**Comment by pauloborba** [comment]
> > it would also be nice to check how the cases above behave in a purely textual merge. does diffj invokes diff3 for method bodies?
> 
> I don't think it does, because it uses the syntax tree inside the method.
> 
> > it's nice to have the syntactic diff. but for detecting lines changed, diff3 could actually be a better option. so one alternative would be to use the two tools in combination (unless diffj already invokes diff3 for method bodies).
> 
> So we would use DiffJ only to check line numbers and which method the changes were, and use a textual diff tool to resolve if the changes where adds, changes or removals? I think this could be a solution

DiffJ would only be used to check if the changes occurred inside the same method. Textual diff would be used for everything else (It is likely be more reliable).

**Comment by rafaelmotaalves** [comment]
But we need to know which lines belong to the modified methods, to do this we can use only the line numbers from diffj.

**Comment by pauloborba** [comment]
right @rafaelmotaalves. for knowing which lines have been changed, it might be better to rely on the textual diff results

**Comment by rafaelmotaalves** [comment]
actually, what I meant is that diffj doesn't output methods line intervals, so we would need to the need diffj's changed line numbers to know which lines from textual diff output are inside a given method.

**Comment by pauloborba** [comment]
that's what I understood from what you have said before

**Comment by rafaelmotaalves** [comment]
ok, got it, will try to implement that way.
